[colors.primary]
background = "#190000"
foreground = "#c3c1c1"

[colors.cursor]
text = "#190000"
cursor = "#c3c1c1"

[colors.vi_mode_cursor]
text = "#190000"
cursor = "#c3c1c1"

[colors.search.matches]
foreground = "#190000"
background = "#c3c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#c00000"
background = "#968c8c"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#190000"
red = "#c1a500"
green = "#db007c"
yellow = "#d6bb00"
blue = "#fca700"
magenta = "#ff601a"
cyan = "#ffc525"
white = "#968c8c"

[colors.bright]
black = "#c00000"
red = "#ffcc02"
green = "#ff269f"
yellow = "#ffe81f"
blue = "#fec552"
magenta = "#ffa579"
cyan = "#ffdb88"
white = "#c3c1c1"

[colors.dim]
black = "#c3c1c1"
red = "#ffcc02"
green = "#ffa579"
yellow = "#ffe81f"
blue = "#fec552"
magenta = "#ff269f"
cyan = "#ffdb88"
white = "#c00000"

