[colors]
background = '#1900008e'
black = '#190000'
blue = '#c1a500'
cursor = '#c3c1c1'
cyan = '#db007c'
foreground = '#c3c1c1'
green = '#d6bb00'
magenta = '#fca700'
red = '#ff601a'
tabs = '#c3c1c1'
tabs-active = '#ffc525'
white = '#c3c1c1'
yellow = '#968c8c'
dim-black = '#1900008e'
dim-blue = '#c1a5008e'
dim-cyan = '#db007c8e'
dim-foreground = '#c3c1c18e'
dim-green = '#d6bb008e'
dim-magenta = '#fca7008e'
dim-red = '#ff601a8e'
dim-white = '#ffc5258e'
dim-yellow = '#968c8c8e'
light-black = '#ffcc02'
light-blue = '#ff269f'
light-cyan = '#ffe81f'
light-foreground = '#fec552'
light-green = '#ffa579'
light-magenta = '#ffdb88'
light-red = '#c3c1c1'
light-white = '#ffcc02'
light-yellow = '#ff269f'
