# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lab"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = false

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
#saturation = 50

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }
colors-json = { template = 'colors.json', target = '~/.cache/wallust/colors.json' }
colors-sh   = { template = 'colors.sh', target = '~/.cache/wallust/colors.sh' }
colors-css  = { template = 'colors.css', target = '~/.cache/wallust/colors.css' }
colors-xres = { template = 'colors.Xresources', target = '~/.cache/wallust/colors.Xresources' }

# Terminals & Shells
kitty     = { template = 'colors-kitty.conf', target = '~/.cache/wallust/colors-kitty.conf' }
foot      = { template = 'colors-foot.ini', target = '~/.cache/wallust/colors-foot.ini' }
alacritty = { template = 'colors-alacritty.toml', target = '~/.cache/wallust/colors-alacritty.toml' }
ghostty   = { template = 'ghostty.conf', target = '~/.cache/wallust/ghostty.conf' }
fish      = { template = 'colors.fish', target = '~/.cache/wallust/colors.fish' }
wal-rem   = { template = 'wal', target = '~/.cache/wallust/wal' }
sequences = { template = 'sequences', target = '~/.cache/wallust/sequences' }

# WM & Bars
hyprland = { template = 'colors-hyprland.conf', target = '~/.cache/wallust/colors-hyprland.conf' }
waybar   = { template = 'colors-waybar.css', target = '~/.cache/wallust/colors-waybar.css' }
rofi     = { template = 'colors-rofi-dark.rasi', target = '~/.cache/wallust/colors-rofi-dark.rasi' }
mako     = { template = 'colors-mako', target = '~/.cache/wallust/colors-mako' }

# Apps
zathura   = { template = 'colors-zathura', target = '~/.cache/wallust/colors-zathura' }
spicetify = { template = 'colors-spicetify.ini', target = '~/.cache/wallust/colors-spicetify.ini' }
cava      = { template = 'cava.conf', target = '~/.cache/wallust/cava.conf' }
zed       = { template = 'colors-zed.json', target = '~/.cache/wallust/colors-zed.json' }
vscode    = { template = 'colors-vscode.json', target = '~/.cache/wallust/colors-vscode.json' }
nvim = {template = 'colors-wal.vim',target = '.cache/wallust/colors-wal.vim'}

[bin]
post_hook = 'swww img "{{wallpaper}}"'
